version: '3'
services:
  app:
    container_name: mdl_php5.6
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ./public_html:/var/www/html
      - ./data/moodledata:/var/www/moodledata
    ports:
      - '80:80'
    networks:
      - mdlnet_303

  mysql:
    container_name: mdl_mysql5.6
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
      - mdlnet_303

networks:
  mdlnet_303:
